- src/lib.rs
Hello,
my enum looks like that:
```rust
#[derive(IntoPrimitive, TryFromPrimitive, Copy, Clone, PartialEq, Debug)]
#[repr(u8)]
pub enum BasicTokenNoPrefix {
EndOfTokenisedLine = 0,
StatementSeparator = 1,
[...]
Error,
[...]
}
```
and I obtain this compilation error when using it:
```
error: ambiguous associated item
--> src/basic/tokens.rs:7:10
|
7 | #[derive(IntoPrimitive, TryFromPrimitive, Copy, Clone, PartialEq, Debug)]
|          ^^^^^^^^^^^^^^^^
|
= note: #[deny(ambiguous_associated_items)] on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #57644 <https://github.com/rust-lang/rust/issues/57644>
note: `Error` could refer to variant defined here
--> …
```
> Fix  `ambiguous_associated_items` case

- README.md
- src/lib.rs
I wanted to use num_enum in an embedded context where the std crate is not available.
Fortunately, all it uses from std are re-exports from alloc and core,
so this was very straight forward.
This essentially should be no change for existing users, while allowing
the use in no_std environments.
> no_std compability

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- tests/lib.rs
The main motivation for this PR is to stop using `String` as the `Error` type for the `TryFrom` conversion, since it means that a failed conversion will unconditionally heap-allocate an error message; such error message deserves to be lazily generated from within the `Display` `impl` of a custom `Error` type.
On top of that, the code has been simplified in some places for clarity, and the error messages generated by the `proc-macro` now have a more precise `Span` information.
Finally, the code in `README.md` is now automagically tested, which has led to fixing some errors in it.
> Removed unconditional heap-allocation on TryFrom failure

- num_enum_derive/src/lib.rs
Co-authored-by: @glchapman
Fixes #11 
So the enum
```rust
#[derive(TryFromPrimitive)]
#[repr(u8)]
enum Example { A, B, C, D, E, F = 8, G, H, I, J, K, L, M, }
```
now generates:
```rust
impl ::num_enum::TryFromPrimitive for Example {
// ...
fn try_from_primitive(number: Self::Primitive)
->
::core::result::Result<Self,
::num_enum::TryFromPrimitiveError<Self>> {
#![allow(non_upper_case_globals)]
const A: u8 = 0;
const B: u8 = u8::wrapping_add(A, 1);
const C: u8 = u8::wrapping_add(B, 1);
const D: u8 = u8::wrapping_add(C, 1);
const E: u8 = u8::wrapping_add(D, 1);
const F: u8 = 8;
const G: u8 = u8::wrapping_add(F, 1);
const H: u8 = u8::wrapping_add(G, 1);
const I: u8 = u8::wrapping_add(H, 1);
const J: u8 = u8::wrapping_add(I, 1);
const K: u8 = u8::wrapping_add(J, 1);
const L: u8 = …
```
> Improved constant values generated code (issue #11)

- .travis.yml
Cargo stopped allowing feature flags in virtual manifests.
> Pass manifest path on CI

- num_enum/Cargo.toml
There are no changes in this release of derivative; it just brings in
transitive dependencies on stable releases of proc-macro2/syn/quote.
> Upgrade to derivative 2.0

- .travis.yml
- Cargo.toml
- num_enum_derive/Cargo.toml
- num_enum_derive/src/lib.rs
- renamed_num_enum/Cargo.toml
- serde_example/Cargo.toml
- serde_example/src/lib.rs
The proc-macro-crate depends on toml, which in turn depends on serde
_with_ std. Only depend on proc-macro-crate if std is enabled.
This means that no_std consumer of num_enum cannot rename their num_enum
dependency. This seems like a reasonable restriction.
Works around https://github.com/rust-lang/cargo/issues/5730
Fixes #18
> Fix no_std support if serde is depended on

- num_enum/tests/from_primitive.rs
- num_enum/tests/into_primitive.rs
- num_enum/tests/renamed_num_enum.rs
- num_enum/tests/try_from_primitive.rs
- num_enum/tests/unsafe_from_primitive.rs
- renamed_num_enum/Cargo.toml
- renamed_num_enum/src/lib.rs
When #27 was submitted, I was worried that some of our expansions did not use fully qualified paths such as `::core`. Although it currently isn't the case (👏 good job, us! 😄), it's an oversight that could easily creep in at any moment. I have thus added "problematic" `mod alloc {} mod core {} mod num_enum {} mod std {}` to most of our expansions to make sure that does not happen.
- Oh, and I also made sure the `renamed_...` crate test also featured a `no_std` run, although with the rename being then reverted (since we don't support renaming when in a `no_std` context). Just to be extra safe 🙂
> Ensure tests detect a regression of #27 + re-enabled no_std test back

- num_enum/tests/try_build.rs
- num_enum/tests/try_build/compile_fail/conflicting_derive.stderr_beta
1.48 got promoted to beta.
If we were being really precise, this should probably use version
numbers rather than channels, but *shrug* this will do.
> Fix beta tests

- num_enum/tests/try_build.rs
- num_enum/tests/try_build/compile_fail/conflicting_derive.stderr_nightly
https://github.com/rust-lang/rust/pull/83954 removed the trailing :.
> Fix nightly test expectation

- README.md
Both `std::convert::From::from` and `num_enum::FromPrimitive::from_primitive` are safe to call.
> Remove unnecessary `unsafe` blocks from FromPrimitive example

- num_enum/src/lib.rs
Hide this behind two layers of cfg_attr so that it still parses
pre-1.54.0.
Also, make the fallback text link be linkified.
When 1.54.0 hits stable I'll de-conditionalise this and make a 0.6.0
release with a bumped MSRV.
> Use extended_key_value_attributes for rustdoc

- num_enum/Cargo.toml
- num_enum/src/lib.rs
Derivative is only used to generate trait implementations for a single struct, to get around a standard library issue.  While manually expanding the trait implementations makes the code slightly longer, it allows removing a dependency and speeding up the build time of crates that depend on this.
> Remove derivative dependency

- num_enum/tests/try_build/compile_fail/alternative_exprs.rs
- num_enum/tests/try_build/compile_fail/alternative_exprs.stderr
- num_enum/tests/try_from_primitive.rs
- num_enum_derive/src/lib.rs
While preserving favouring literal values where possible.
Fixes #94 
The story here is:
https://github.com/illicitonion/num_enum/pull/89 tried to simplify the generated code (which, among other things, made rustc not stack overflow when codegening for large enums).
Unfortunately, it assumed that all explicit discriminants were literals (and non-negative ones, as `-123` parses as a `UnaryExpr` not a `Literal`).
And further unfortunately, because of a typo in a `#[cfg(feature)]` attached to the only tests we had for non-literal enums, we weren't running those tests (this PR re-enables them and adds some which aren't feature gated, and https://github.com/illicitonion/num_enum/pull/95 will ensure we don't regress in this way again).
This PR attempts to preserve the "prefer just using literals …
> Support non-literal discriminant values

- num_enum/tests/try_build/compile_fail/alternative_clashes_with_its_discriminant.rs
- num_enum/tests/try_build/compile_fail/alternative_clashes_with_its_discriminant.stderr
- num_enum/tests/try_build/compile_fail/alternative_clashes_with_variant_out_of_order.rs
- num_enum/tests/try_build/compile_fail/alternative_clashes_with_variant_out_of_order.stderr
- num_enum_derive/src/lib.rs
Fix #97.
Small PR to underline the correct alternative variant when they are not written in order.
> Underline the correct alternative variant in case of error.

- num_enum/tests/from_primitive.rs
- num_enum_derive/src/lib.rs
Large enums realistically will never be naturally exhaustive due to their size. The shift is now done as a checked shift and when the shift fails it will default to not naturally exhaustive, requiring the default attribute, even if it were exhaustive. (I want to meet the person who manages to write down 2^64 enum values or more)
> fix(#102): Fixed shift error on >64 bit enums

- Cargo.lock.msrv
- README.md
- num_enum/Cargo.toml
- num_enum/src/lib.rs
- num_enum/tests/from_primitive.rs
- num_enum/tests/try_build/compile_fail/conflicting_derive.stderr
- num_enum/tests/try_from_primitive.rs
- num_enum_derive/Cargo.toml
- num_enum_derive/src/lib.rs
If exhaustive behaviour is desired, FromPrimitive should be derived
instead.
Because these traits are exclusive, there's no room for ambiguity here -
either TryFromPrimitive is derived and defaults are ignored, or
FromPrimitive is derived and defaults are paid attention to.
This is, however, a breaking change, as it changes the implementation of
TryFromPrimitive significantly.
Fixes https://github.com/illicitonion/num_enum/issues/75
Fixes https://github.com/illicitonion/num_enum/issues/31
> TryFromPrimitive ignores default attributes

- .github/workflows/msrv-build.yml
- Cargo.lock.msrv
- num_enum_derive/Cargo.toml
- num_enum_derive/src/lib.rs
This should deal with all of the breakages from updating to `syn` v2
This update would also require an MSRV bump, since it looks like the current MSRV is 1.54 while `syn` bumped up to 1.56 (2021 edition)
> Update syn to v2

- num_enum_derive/Cargo.toml
It doesn't seem like anything crucial happened in 2..=2.0.10
> Reduce minimum syn version to 2

- num_enum/tests/from_primitive.rs
- num_enum_derive/src/lib.rs
Always return false in those cases (as is the case for u32, i32, u64, and i64).
Without this, `FromPrimitive` is not usable with `repr(usize)`.
> Fix is_naturally_exhaustive test for usize/isize.

- Cargo.lock.msrv
- num_enum/src/lib.rs
- num_enum_derive/Cargo.toml
I'm not sure why we were manually implementing these, but we don't need to, and clippy on nightly has started complaining about the Clone impl.
> TryFromPrimitiveError: Derive a bunch of traits

- README.md
Also fix up heading structures
> Document custom error types in README

- .github/workflows/features.yml
- .github/workflows/minimal-versions.yml
- .github/workflows/msrv-build.yml
- .github/workflows/presubmit.yml
This moves to the latest version (as of now).
> ci: Update to `actions/checkout@v4`.

- .github/workflows/msrv-build.yml
- Cargo.lock.msrv
- num_enum/Cargo.toml
- num_enum_derive/Cargo.toml
- serde_example/Cargo.toml
- stress_tests/Cargo.toml
This necessitates bumping MSRV to 1.70.0, which is a significant change from 1.56.0.
1.70.0 was more than a year ago, and seems like a reasonable bump, but it's a bit unfortunate that we're doing this bump only for a test-only dependency.
As we're not actually changing any production code here, things are likely to continue to work with older rust versions, but we will not continue testing this, and make no promises versions older than 1.70.0 will keep working.
> Bump trybuild to 1.0.98, and MSRV to 1.70.0

- num_enum/tests/from_primitive.rs
- num_enum_derive/src/parsing.rs
This commit filters out catch_all variant in the `variant_idents` and `variant_expressions` of `EnumInfo`. This allows the catch_all variant to be in the middle of enum.
A test of catch_all variant in the middle of enum is also added.
Fix #149
> fix: filter catch_all variant in EnumInfo methods

- num_enum/Cargo.toml
We haven't used travis in a number of years, and also badges are no longer a Cargo.toml thing.
> Remove travis badge

- num_enum/Cargo.toml
- num_enum/src/lib.rs
The `Error` trait has been in `core` since 1.81.
This PR implements `Error` for `TryFromPrimitiveError` even without the `std` feature for toolchains since 1.81.
> Use `core::error::Error` when available

- num_enum/tests/try_build/compile_fail/from_unchecked_deprecated_warning.stderr_nightly
https://github.com/rust-lang/rust/commit/aa9767290e46c9c73fa1fd3abb52277b4d07cfae started aligning numbers to the right.
> Fix nightly test expectations
